//  Find the difference

// You are given two strings s and t. String t is generated by random shuffling string s and then add one more letter at a random position. Return the letter that was added to t.

// Example 1:
// Input: s = "abcd", t = "abcde"
// Output: "e"
// Explanation: 'e' is the letter that was added.

// Example 2:
// Input: s = "", t = "y"
// Output: "y"

class Solution {
    public char findTheDifference(String s, String t) {
        int result = 0;
        
        // XOR all characters in string s
        for (char c : s.toCharArray()) {
            result ^= c;
        }   
        // XOR all characters in string t
        for (char c : t.toCharArray()) {
            result ^= c;
        } 
        // The result will be the extra character in t
        return (char) result;
    }
}
